apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        imagePullPolicy: Always
        ports:
        - containerPort: 1883
          hostPort: 1883
        volumeMounts:
        - name: mosquitto
          mountPath: /mosquitto/config/
        - name: localtime
          mountPath: /etc/localtime
        - name: mosquitto
          mountPath: /srv/mqtt/data
        - name: mosquitto
          mountPath: /srv/mqtt/log
      volumes:
      - name: mosquitto
        persistentVolumeClaim:
          claimName: mosquitto
      - name: localtime
        hostPath:
          path: /etc/localtime
